In [1]:
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import linear_model

In [8]:
data=pd.read_csv('data1.csv')
data

a    b
0   1  1.0
1   2  1.5
2   3  2.0
3   4  3.5
4   5  3.0
5   6  3.5
6   7  4.0
7   8  4.5
8   9  5.0
9  10  4.5

In [15]:
X=data[['a']].values#.reshape(-1,1)
X
y=data[['b']].values#.reshape(-1,1)
y

array([[1. ],
       [1.5],
       [2. ],
       [3.5],
       [3. ],
       [3.5],
       [4. ],
       [4.5],
       [5. ],
       [4.5]])

In [15]:
train_test_split?

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [17]:
reg=linear_model.Ridge(alpha=0.5)

In [18]:
X_train.shape==y_train.shape

True

In [19]:
reg.fit(X_train,y_train)

Ridge(alpha=0.5)

In [20]:
y_pred=reg.predict(X_test)

In [21]:
y1=reg.predict([[11]])
y1

array([[5.4538835]])

In [15]:
reg1=linear_model.Lasso(alpha=0.5)

In [16]:
reg1.fit(X_train,y_train)

Lasso(alpha=0.5)

In [17]:
y2=reg1.predict([[11]])
y2

array([5.11937378])

In [18]:
reg2=linear_model.ElasticNet(alpha=0.5)

In [19]:
reg2.fit(X_train,y_train)

ElasticNet(alpha=0.5)

In [49]:
y3=reg2.predict([[11]])
y3

array([5.23149905])

In [2]:
data2=pd.read_csv('data2.csv')
data2

x1  x2  y1
0   3.0   1   0
1   3.7   6   1
2   2.7   2   0
3   3.3   2   1
4   4.0   3   1
5   3.9   4   1
6   3.3   3   0
7   3.7   5   1
8   3.9   4   1
9   3.7   6   1
10  2.3   1   0
11  3.3   4   1
12  3.3   5   1
13  1.7   1   0
14  2.7   3   0
15  3.7   5   1
16  3.7   6   1
17  3.3   4   0

In [22]:
X=data2[['x1','x2']].values#.reshape(-1,1)
y=data2['y1'].values#.reshape(-1,1)

In [29]:
reg3=linear_model.LogisticRegression(random_state=0)#,solver='lbfgs',multi_class='auto')

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [31]:
reg3.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [32]:
y_pred=reg3.predict(X_test)

In [34]:
y4=reg3.predict([[2.9,7]])
y4

array([1])